name: Build & Deploy to GitHub Pages

on:
  push:
    branches: [$default-branch]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Prepare public assets folder
        run: mkdir -p public/posts-assets

      - name: Build HTML, index & metadata
        working-directory: .tools
        run: |
          # preload remote imports
          deno cache generate-html.ts generate-index.ts update-metadata.ts

          deno run build:html
          deno run build:index
          deno run build:metadata

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
